//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddCliente.ReferenciaServidor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servidoredd2/", ConfigurationName="ReferenciaServidor.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servidoredd2/reiniciarArbol", ReplyAction="*")]
        void reiniciarArbol();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servidoredd2/reiniciarMatriz", ReplyAction="*")]
        void reiniciarMatriz();
        
        // CODEGEN: Generating message contract since element name UsuariosgrafoResult from namespace http://servidoredd2/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servidoredd2/Usuariosgrafo", ReplyAction="*")]
        EddCliente.ReferenciaServidor.UsuariosgrafoResponse Usuariosgrafo(EddCliente.ReferenciaServidor.UsuariosgrafoRequest request);
        
        // CODEGEN: Generating message contract since element name espejoArbolResult from namespace http://servidoredd2/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servidoredd2/espejoArbol", ReplyAction="*")]
        EddCliente.ReferenciaServidor.espejoArbolResponse espejoArbol(EddCliente.ReferenciaServidor.espejoArbolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servidoredd2/getGArbol", ReplyAction="*")]
        byte getGArbol(int i);
        
        // CODEGEN: Generating message contract since element name MatrizGrafoResult from namespace http://servidoredd2/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servidoredd2/MatrizGrafo", ReplyAction="*")]
        EddCliente.ReferenciaServidor.MatrizGrafoResponse MatrizGrafo(EddCliente.ReferenciaServidor.MatrizGrafoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servidoredd2/getGMatriz", ReplyAction="*")]
        byte getGMatriz(int i);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://servidoredd2/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servidoredd2/IniciarSesion", ReplyAction="*")]
        EddCliente.ReferenciaServidor.IniciarSesionResponse IniciarSesion(EddCliente.ReferenciaServidor.IniciarSesionRequest request);
        
        // CODEGEN: Generating message contract since element name devolverResult from namespace http://servidoredd2/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servidoredd2/devolver", ReplyAction="*")]
        EddCliente.ReferenciaServidor.devolverResponse devolver(EddCliente.ReferenciaServidor.devolverRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://servidoredd2/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servidoredd2/InsertarArbol", ReplyAction="*")]
        EddCliente.ReferenciaServidor.InsertarArbolResponse InsertarArbol(EddCliente.ReferenciaServidor.InsertarArbolRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://servidoredd2/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servidoredd2/InsertarJuego", ReplyAction="*")]
        EddCliente.ReferenciaServidor.InsertarJuegoResponse InsertarJuego(EddCliente.ReferenciaServidor.InsertarJuegoRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://servidoredd2/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servidoredd2/InsertarMatriz", ReplyAction="*")]
        EddCliente.ReferenciaServidor.InsertarMatrizResponse InsertarMatriz(EddCliente.ReferenciaServidor.InsertarMatrizRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://servidoredd2/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servidoredd2/ModificarUsuario", ReplyAction="*")]
        EddCliente.ReferenciaServidor.ModificarUsuarioResponse ModificarUsuario(EddCliente.ReferenciaServidor.ModificarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://servidoredd2/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://servidoredd2/EliminarUsuario", ReplyAction="*")]
        EddCliente.ReferenciaServidor.EliminarUsuarioResponse EliminarUsuario(EddCliente.ReferenciaServidor.EliminarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsuariosgrafoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Usuariosgrafo", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.UsuariosgrafoRequestBody Body;
        
        public UsuariosgrafoRequest() {
        }
        
        public UsuariosgrafoRequest(EddCliente.ReferenciaServidor.UsuariosgrafoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UsuariosgrafoRequestBody {
        
        public UsuariosgrafoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsuariosgrafoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsuariosgrafoResponse", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.UsuariosgrafoResponseBody Body;
        
        public UsuariosgrafoResponse() {
        }
        
        public UsuariosgrafoResponse(EddCliente.ReferenciaServidor.UsuariosgrafoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servidoredd2/")]
    public partial class UsuariosgrafoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] UsuariosgrafoResult;
        
        public UsuariosgrafoResponseBody() {
        }
        
        public UsuariosgrafoResponseBody(byte[] UsuariosgrafoResult) {
            this.UsuariosgrafoResult = UsuariosgrafoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class espejoArbolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="espejoArbol", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.espejoArbolRequestBody Body;
        
        public espejoArbolRequest() {
        }
        
        public espejoArbolRequest(EddCliente.ReferenciaServidor.espejoArbolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class espejoArbolRequestBody {
        
        public espejoArbolRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class espejoArbolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="espejoArbolResponse", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.espejoArbolResponseBody Body;
        
        public espejoArbolResponse() {
        }
        
        public espejoArbolResponse(EddCliente.ReferenciaServidor.espejoArbolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servidoredd2/")]
    public partial class espejoArbolResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] espejoArbolResult;
        
        public espejoArbolResponseBody() {
        }
        
        public espejoArbolResponseBody(byte[] espejoArbolResult) {
            this.espejoArbolResult = espejoArbolResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatrizGrafoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MatrizGrafo", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.MatrizGrafoRequestBody Body;
        
        public MatrizGrafoRequest() {
        }
        
        public MatrizGrafoRequest(EddCliente.ReferenciaServidor.MatrizGrafoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servidoredd2/")]
    public partial class MatrizGrafoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nivel;
        
        public MatrizGrafoRequestBody() {
        }
        
        public MatrizGrafoRequestBody(int nivel) {
            this.nivel = nivel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatrizGrafoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MatrizGrafoResponse", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.MatrizGrafoResponseBody Body;
        
        public MatrizGrafoResponse() {
        }
        
        public MatrizGrafoResponse(EddCliente.ReferenciaServidor.MatrizGrafoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servidoredd2/")]
    public partial class MatrizGrafoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] MatrizGrafoResult;
        
        public MatrizGrafoResponseBody() {
        }
        
        public MatrizGrafoResponseBody(byte[] MatrizGrafoResult) {
            this.MatrizGrafoResult = MatrizGrafoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IniciarSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IniciarSesion", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.IniciarSesionRequestBody Body;
        
        public IniciarSesionRequest() {
        }
        
        public IniciarSesionRequest(EddCliente.ReferenciaServidor.IniciarSesionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servidoredd2/")]
    public partial class IniciarSesionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public IniciarSesionRequestBody() {
        }
        
        public IniciarSesionRequestBody(string nickname, string contraseña) {
            this.nickname = nickname;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IniciarSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IniciarSesionResponse", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.IniciarSesionResponseBody Body;
        
        public IniciarSesionResponse() {
        }
        
        public IniciarSesionResponse(EddCliente.ReferenciaServidor.IniciarSesionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servidoredd2/")]
    public partial class IniciarSesionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IniciarSesionResult;
        
        public IniciarSesionResponseBody() {
        }
        
        public IniciarSesionResponseBody(bool IniciarSesionResult) {
            this.IniciarSesionResult = IniciarSesionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class devolverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="devolver", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.devolverRequestBody Body;
        
        public devolverRequest() {
        }
        
        public devolverRequest(EddCliente.ReferenciaServidor.devolverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class devolverRequestBody {
        
        public devolverRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class devolverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="devolverResponse", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.devolverResponseBody Body;
        
        public devolverResponse() {
        }
        
        public devolverResponse(EddCliente.ReferenciaServidor.devolverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servidoredd2/")]
    public partial class devolverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string devolverResult;
        
        public devolverResponseBody() {
        }
        
        public devolverResponseBody(string devolverResult) {
            this.devolverResult = devolverResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarArbolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarArbol", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.InsertarArbolRequestBody Body;
        
        public InsertarArbolRequest() {
        }
        
        public InsertarArbolRequest(EddCliente.ReferenciaServidor.InsertarArbolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servidoredd2/")]
    public partial class InsertarArbolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int conexion;
        
        public InsertarArbolRequestBody() {
        }
        
        public InsertarArbolRequestBody(string nickname, string contraseña, string correo, int conexion) {
            this.nickname = nickname;
            this.contraseña = contraseña;
            this.correo = correo;
            this.conexion = conexion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarArbolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarArbolResponse", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.InsertarArbolResponseBody Body;
        
        public InsertarArbolResponse() {
        }
        
        public InsertarArbolResponse(EddCliente.ReferenciaServidor.InsertarArbolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertarArbolResponseBody {
        
        public InsertarArbolResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarJuegoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarJuego", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.InsertarJuegoRequestBody Body;
        
        public InsertarJuegoRequest() {
        }
        
        public InsertarJuegoRequest(EddCliente.ReferenciaServidor.InsertarJuegoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servidoredd2/")]
    public partial class InsertarJuegoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oponente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int desplegadas;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int sobrevivientes;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int destruidas;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int gano;
        
        public InsertarJuegoRequestBody() {
        }
        
        public InsertarJuegoRequestBody(string nickname, string oponente, int desplegadas, int sobrevivientes, int destruidas, int gano) {
            this.nickname = nickname;
            this.oponente = oponente;
            this.desplegadas = desplegadas;
            this.sobrevivientes = sobrevivientes;
            this.destruidas = destruidas;
            this.gano = gano;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarJuegoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarJuegoResponse", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.InsertarJuegoResponseBody Body;
        
        public InsertarJuegoResponse() {
        }
        
        public InsertarJuegoResponse(EddCliente.ReferenciaServidor.InsertarJuegoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertarJuegoResponseBody {
        
        public InsertarJuegoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarMatrizRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarMatriz", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.InsertarMatrizRequestBody Body;
        
        public InsertarMatrizRequest() {
        }
        
        public InsertarMatrizRequest(EddCliente.ReferenciaServidor.InsertarMatrizRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servidoredd2/")]
    public partial class InsertarMatrizRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int fila;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int columna;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nickname;
        
        public InsertarMatrizRequestBody() {
        }
        
        public InsertarMatrizRequestBody(int fila, int columna, string nombre, string nickname) {
            this.fila = fila;
            this.columna = columna;
            this.nombre = nombre;
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarMatrizResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarMatrizResponse", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.InsertarMatrizResponseBody Body;
        
        public InsertarMatrizResponse() {
        }
        
        public InsertarMatrizResponse(EddCliente.ReferenciaServidor.InsertarMatrizResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertarMatrizResponseBody {
        
        public InsertarMatrizResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarUsuario", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.ModificarUsuarioRequestBody Body;
        
        public ModificarUsuarioRequest() {
        }
        
        public ModificarUsuarioRequest(EddCliente.ReferenciaServidor.ModificarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servidoredd2/")]
    public partial class ModificarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nickname2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contraseña;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string correo;
        
        public ModificarUsuarioRequestBody() {
        }
        
        public ModificarUsuarioRequestBody(string nickname, string nickname2, string contraseña, string correo) {
            this.nickname = nickname;
            this.nickname2 = nickname2;
            this.contraseña = contraseña;
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarUsuarioResponse", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.ModificarUsuarioResponseBody Body;
        
        public ModificarUsuarioResponse() {
        }
        
        public ModificarUsuarioResponse(EddCliente.ReferenciaServidor.ModificarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificarUsuarioResponseBody {
        
        public ModificarUsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuario", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.EliminarUsuarioRequestBody Body;
        
        public EliminarUsuarioRequest() {
        }
        
        public EliminarUsuarioRequest(EddCliente.ReferenciaServidor.EliminarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servidoredd2/")]
    public partial class EliminarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public EliminarUsuarioRequestBody() {
        }
        
        public EliminarUsuarioRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuarioResponse", Namespace="http://servidoredd2/", Order=0)]
        public EddCliente.ReferenciaServidor.EliminarUsuarioResponseBody Body;
        
        public EliminarUsuarioResponse() {
        }
        
        public EliminarUsuarioResponse(EddCliente.ReferenciaServidor.EliminarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EliminarUsuarioResponseBody {
        
        public EliminarUsuarioResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : EddCliente.ReferenciaServidor.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<EddCliente.ReferenciaServidor.WebServiceSoap>, EddCliente.ReferenciaServidor.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void reiniciarArbol() {
            base.Channel.reiniciarArbol();
        }
        
        public void reiniciarMatriz() {
            base.Channel.reiniciarMatriz();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EddCliente.ReferenciaServidor.UsuariosgrafoResponse EddCliente.ReferenciaServidor.WebServiceSoap.Usuariosgrafo(EddCliente.ReferenciaServidor.UsuariosgrafoRequest request) {
            return base.Channel.Usuariosgrafo(request);
        }
        
        public byte[] Usuariosgrafo() {
            EddCliente.ReferenciaServidor.UsuariosgrafoRequest inValue = new EddCliente.ReferenciaServidor.UsuariosgrafoRequest();
            inValue.Body = new EddCliente.ReferenciaServidor.UsuariosgrafoRequestBody();
            EddCliente.ReferenciaServidor.UsuariosgrafoResponse retVal = ((EddCliente.ReferenciaServidor.WebServiceSoap)(this)).Usuariosgrafo(inValue);
            return retVal.Body.UsuariosgrafoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EddCliente.ReferenciaServidor.espejoArbolResponse EddCliente.ReferenciaServidor.WebServiceSoap.espejoArbol(EddCliente.ReferenciaServidor.espejoArbolRequest request) {
            return base.Channel.espejoArbol(request);
        }
        
        public byte[] espejoArbol() {
            EddCliente.ReferenciaServidor.espejoArbolRequest inValue = new EddCliente.ReferenciaServidor.espejoArbolRequest();
            inValue.Body = new EddCliente.ReferenciaServidor.espejoArbolRequestBody();
            EddCliente.ReferenciaServidor.espejoArbolResponse retVal = ((EddCliente.ReferenciaServidor.WebServiceSoap)(this)).espejoArbol(inValue);
            return retVal.Body.espejoArbolResult;
        }
        
        public byte getGArbol(int i) {
            return base.Channel.getGArbol(i);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EddCliente.ReferenciaServidor.MatrizGrafoResponse EddCliente.ReferenciaServidor.WebServiceSoap.MatrizGrafo(EddCliente.ReferenciaServidor.MatrizGrafoRequest request) {
            return base.Channel.MatrizGrafo(request);
        }
        
        public byte[] MatrizGrafo(int nivel) {
            EddCliente.ReferenciaServidor.MatrizGrafoRequest inValue = new EddCliente.ReferenciaServidor.MatrizGrafoRequest();
            inValue.Body = new EddCliente.ReferenciaServidor.MatrizGrafoRequestBody();
            inValue.Body.nivel = nivel;
            EddCliente.ReferenciaServidor.MatrizGrafoResponse retVal = ((EddCliente.ReferenciaServidor.WebServiceSoap)(this)).MatrizGrafo(inValue);
            return retVal.Body.MatrizGrafoResult;
        }
        
        public byte getGMatriz(int i) {
            return base.Channel.getGMatriz(i);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EddCliente.ReferenciaServidor.IniciarSesionResponse EddCliente.ReferenciaServidor.WebServiceSoap.IniciarSesion(EddCliente.ReferenciaServidor.IniciarSesionRequest request) {
            return base.Channel.IniciarSesion(request);
        }
        
        public bool IniciarSesion(string nickname, string contraseña) {
            EddCliente.ReferenciaServidor.IniciarSesionRequest inValue = new EddCliente.ReferenciaServidor.IniciarSesionRequest();
            inValue.Body = new EddCliente.ReferenciaServidor.IniciarSesionRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.contraseña = contraseña;
            EddCliente.ReferenciaServidor.IniciarSesionResponse retVal = ((EddCliente.ReferenciaServidor.WebServiceSoap)(this)).IniciarSesion(inValue);
            return retVal.Body.IniciarSesionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EddCliente.ReferenciaServidor.devolverResponse EddCliente.ReferenciaServidor.WebServiceSoap.devolver(EddCliente.ReferenciaServidor.devolverRequest request) {
            return base.Channel.devolver(request);
        }
        
        public string devolver() {
            EddCliente.ReferenciaServidor.devolverRequest inValue = new EddCliente.ReferenciaServidor.devolverRequest();
            inValue.Body = new EddCliente.ReferenciaServidor.devolverRequestBody();
            EddCliente.ReferenciaServidor.devolverResponse retVal = ((EddCliente.ReferenciaServidor.WebServiceSoap)(this)).devolver(inValue);
            return retVal.Body.devolverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EddCliente.ReferenciaServidor.InsertarArbolResponse EddCliente.ReferenciaServidor.WebServiceSoap.InsertarArbol(EddCliente.ReferenciaServidor.InsertarArbolRequest request) {
            return base.Channel.InsertarArbol(request);
        }
        
        public void InsertarArbol(string nickname, string contraseña, string correo, int conexion) {
            EddCliente.ReferenciaServidor.InsertarArbolRequest inValue = new EddCliente.ReferenciaServidor.InsertarArbolRequest();
            inValue.Body = new EddCliente.ReferenciaServidor.InsertarArbolRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.contraseña = contraseña;
            inValue.Body.correo = correo;
            inValue.Body.conexion = conexion;
            EddCliente.ReferenciaServidor.InsertarArbolResponse retVal = ((EddCliente.ReferenciaServidor.WebServiceSoap)(this)).InsertarArbol(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EddCliente.ReferenciaServidor.InsertarJuegoResponse EddCliente.ReferenciaServidor.WebServiceSoap.InsertarJuego(EddCliente.ReferenciaServidor.InsertarJuegoRequest request) {
            return base.Channel.InsertarJuego(request);
        }
        
        public void InsertarJuego(string nickname, string oponente, int desplegadas, int sobrevivientes, int destruidas, int gano) {
            EddCliente.ReferenciaServidor.InsertarJuegoRequest inValue = new EddCliente.ReferenciaServidor.InsertarJuegoRequest();
            inValue.Body = new EddCliente.ReferenciaServidor.InsertarJuegoRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.oponente = oponente;
            inValue.Body.desplegadas = desplegadas;
            inValue.Body.sobrevivientes = sobrevivientes;
            inValue.Body.destruidas = destruidas;
            inValue.Body.gano = gano;
            EddCliente.ReferenciaServidor.InsertarJuegoResponse retVal = ((EddCliente.ReferenciaServidor.WebServiceSoap)(this)).InsertarJuego(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EddCliente.ReferenciaServidor.InsertarMatrizResponse EddCliente.ReferenciaServidor.WebServiceSoap.InsertarMatriz(EddCliente.ReferenciaServidor.InsertarMatrizRequest request) {
            return base.Channel.InsertarMatriz(request);
        }
        
        public void InsertarMatriz(int fila, int columna, string nombre, string nickname) {
            EddCliente.ReferenciaServidor.InsertarMatrizRequest inValue = new EddCliente.ReferenciaServidor.InsertarMatrizRequest();
            inValue.Body = new EddCliente.ReferenciaServidor.InsertarMatrizRequestBody();
            inValue.Body.fila = fila;
            inValue.Body.columna = columna;
            inValue.Body.nombre = nombre;
            inValue.Body.nickname = nickname;
            EddCliente.ReferenciaServidor.InsertarMatrizResponse retVal = ((EddCliente.ReferenciaServidor.WebServiceSoap)(this)).InsertarMatriz(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EddCliente.ReferenciaServidor.ModificarUsuarioResponse EddCliente.ReferenciaServidor.WebServiceSoap.ModificarUsuario(EddCliente.ReferenciaServidor.ModificarUsuarioRequest request) {
            return base.Channel.ModificarUsuario(request);
        }
        
        public void ModificarUsuario(string nickname, string nickname2, string contraseña, string correo) {
            EddCliente.ReferenciaServidor.ModificarUsuarioRequest inValue = new EddCliente.ReferenciaServidor.ModificarUsuarioRequest();
            inValue.Body = new EddCliente.ReferenciaServidor.ModificarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.nickname2 = nickname2;
            inValue.Body.contraseña = contraseña;
            inValue.Body.correo = correo;
            EddCliente.ReferenciaServidor.ModificarUsuarioResponse retVal = ((EddCliente.ReferenciaServidor.WebServiceSoap)(this)).ModificarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EddCliente.ReferenciaServidor.EliminarUsuarioResponse EddCliente.ReferenciaServidor.WebServiceSoap.EliminarUsuario(EddCliente.ReferenciaServidor.EliminarUsuarioRequest request) {
            return base.Channel.EliminarUsuario(request);
        }
        
        public void EliminarUsuario(string nickname) {
            EddCliente.ReferenciaServidor.EliminarUsuarioRequest inValue = new EddCliente.ReferenciaServidor.EliminarUsuarioRequest();
            inValue.Body = new EddCliente.ReferenciaServidor.EliminarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            EddCliente.ReferenciaServidor.EliminarUsuarioResponse retVal = ((EddCliente.ReferenciaServidor.WebServiceSoap)(this)).EliminarUsuario(inValue);
        }
    }
}
